apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mp-bc-client.fullname" . }}
  labels:
  {{ include "mp-bc-client.labels" . | nindent 4 }}
data:
  MP.BC.CLIENT.PORT: {{ required "A valid .Values.global.mpBCClientPort entry required!" .Values.global.mpBCClientPort | quote }}