apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mp-bc-client.fullname" . }}
  labels:
  {{ include "mp-bc-client.labels" . | nindent 4 }}
data:
  MP_BC_CLIENT_PORT: {{ required "A valid .Values.global.mpBCClientPort entry required!" .Values.global.mpBCClientPort | quote }}
  MP_LOGGING_LEVEL: {{ required "A valid .Values.loggingLevel entry required!" .Values.loggingLevel }}
  MP_ETHEREUM_CLIENT_URL: {{ include "ethereumClientURL" . }}