apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mp-bc-client.fullname" . }}
  labels:
  {{ include "mp-bc-client.labels" . | nindent 4 }}
stringData:
  MP_ETHEREUM_ACCOUNT_PRIVATE_KEY: {{ required "A valid .Values.ethereumAccountPrivateKey entry required!" .Values.ethereumAccountPrivateKey }}
  MP_ETHEREUM_CLIENT_URL: {{ required "A valid .Values.ethereumClientURL entry required!" .Values.ethereumClientURL }}
