apiVersion: v1
kind: Service
metadata:
  name: {{ include "mp-bc-client.fullname" . }}
  labels:
  {{- include "mp-bc-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "A valid .Values.global.mpBCClientPort entry required!" .Values.global.mpBCClientPort }}
      targetPort: {{ required "A valid .Values.global.mpBCClientPort entry required!" .Values.global.mpBCClientPort }}
      protocol: TCP
      name: {{ required "A valid .Values.global.mpBCClientPortName entry required!" .Values.global.mpBCClientPortName }}
  selector:
  {{- include "mp-bc-client.selectorLabels" . | nindent 4 }}
