# Default values for mp-bc-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 543164192837.dkr.ecr.eu-central-1.amazonaws.com/mp-bc-client
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#####################################################################################
################## USER SUPPLIED VALUES IN MAIN VALUES.YAML #########################
#####################################################################################

recreationFlag: 1

global:
  namespaceName: ""
  recreationFlag: 1
  mpBCClientPort: 8070
  mpBCClientPortName: bc-cl-8070

ethereumAccountPrivateKey: ""
ethereumClientURL: ""

service:
  type: ClusterIP

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetAverageCPUUtilization: 70
  targetAverageMemoryUtilization: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  failureThreshold: 30
readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  failureThreshold: 30

#####################################################################################
################## USER SUPPLIED VALUES IN MAIN VALUES.YAML #########################
#####################################################################################

nodeSelector: {}

tolerations: []

affinity: {}
